[package]
name = "katana-explorer"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
anyhow.workspace = true
url.workspace = true
tiny_http.workspace = true
tracing.workspace = true

[build-dependencies]
anyhow.workspace = true
